import { ArrowLeftOutlined } from "@ant-design/icons"
import React from "react"
import { Link } from "react-router-dom"

const PrivacyPolicy = () => {
  return (
    <div className=" bg-gray-100">
      <div className="p-4 sticky top-0 bg-gray-100">
        <Link to="/profile">
          <div className="flex items-center font-bold text-lg">
            <ArrowLeftOutlined className=" text-gray-600" />
            <p className="ml-3 text-gray-600">Kebijakan Privasi</p>
          </div>
        </Link>
      </div>

      <div className="p-4 text-gray-600">
        <div>
          <p className="text-sm text-gray-50">
            Last updated: November 28, 2024
          </p>
        </div>
        <section>
          <p className="text-gray-600">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mt-4 text-gray-600">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        {/* Interpretation and Definitions */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Interpretation and Definitions
          </h2>
          <div className="pl-4">
            <h3 className="text-lg font-medium mb-2">Interpretation</h3>
            <p className="text-gray-600 mb-4">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h3 className="text-lg font-medium mb-2">Definitions</h3>
            <div className="space-y-3">
              {[
                {
                  term: "Account",
                  definition:
                    "A unique account created for You to access our Service or parts of our Service.",
                },
                {
                  term: "Affiliate",
                  definition:
                    'An entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                },
                {
                  term: "Application",
                  definition:
                    "BLJ For Pi, the software program provided by the Company.",
                },
                {
                  term: "Company",
                  definition: "PT. BERKAH LESTARI JAMBI, Kota Jambi.",
                },
                { term: "Country", definition: "Indonesia" },
                {
                  term: "Device",
                  definition:
                    "Any device that can access the Service such as a computer, a cellphone or a digital tablet.",
                },
                {
                  term: "Personal Data",
                  definition:
                    "Any information that relates to an identified or identifiable individual.",
                },
                { term: "Service", definition: "The Application." },
                {
                  term: "Service Provider",
                  definition:
                    "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
                },
                {
                  term: "Usage Data",
                  definition:
                    "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
                },
                {
                  term: "You",
                  definition:
                    "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
                },
              ].map(({ term, definition }) => (
                <div key={term} className="pl-4">
                  <span className="font-medium">{term}</span>
                  <span className="text-gray-600"> means {definition}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Collecting and Using Personal Data */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Collecting and Using Your Personal Data
          </h2>
          <div className="space-y-6">
            <h3 className="text-lg font-medium">Types of Data Collected</h3>

            <div className="pl-4 space-y-6">
              <div>
                <h4 className="font-medium mb-2">Personal Data</h4>
                <p className="text-gray-600">
                  While using Our Service, We may ask You to provide Us with
                  certain personally identifiable information that can be used
                  to contact or identify You. Personally identifiable
                  information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-8 mt-2 space-y-1 text-gray-600">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>
              </div>

              <div>
                <h4 className="font-medium mb-2">Usage Data</h4>
                <p className="text-gray-600">
                  Usage Data is collected automatically when using the Service.
                </p>
                <p className="mt-2 text-gray-600">
                  Usage Data may include information such as Your Device's
                  Internet Protocol address (e.g. IP address), browser type,
                  browser version, the pages of our Service that You visit, the
                  time and date of Your visit, the time spent on those pages,
                  unique device identifiers and other diagnostic data.
                </p>
                <p className="mt-2 text-gray-600">
                  When You access the Service by or through a mobile device, We
                  may collect certain information automatically, including, but
                  not limited to, the type of mobile device You use, Your mobile
                  device unique ID, the IP address of Your mobile device, Your
                  mobile operating system, the type of mobile Internet browser
                  You use, unique device identifiers and other diagnostic data.
                </p>
                <p className="mt-2 text-gray-600">
                  We may also collect information that Your browser sends
                  whenever You visit our Service or when You access the Service
                  by or through a mobile device.
                </p>
              </div>

              <div>
                <h4 className="font-medium mb-2">
                  Information Collected while Using the Application
                </h4>
                <p className="text-gray-600">
                  While using Our Application, in order to provide features of
                  Our Application, We may collect, with Your prior permission:
                </p>
                <ul className="list-disc pl-8 mt-2 space-y-1 text-gray-600">
                  <li>Information regarding your location</li>
                  <li>
                    Information from your Device's phone book (contacts list)
                  </li>
                </ul>
                <p className="mt-2 text-gray-600">
                  We use this information to provide features of Our Service, to
                  improve and customize Our Service. The information may be
                  uploaded to the Company's servers and/or a Service Provider's
                  server or it may be simply stored on Your device.
                </p>
                <p className="mt-2 text-gray-600">
                  You can enable or disable access to this information at any
                  time, through Your Device settings.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Use of Personal Data */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Use of Your Personal Data
          </h2>
          <p className="text-gray-600 mb-4">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc pl-8 space-y-2 text-gray-600">
            <li>
              To provide and maintain our Service, including to monitor the
              usage of our Service.
            </li>
            <li>
              To manage Your Account: to manage Your registration as a user of
              the Service.
            </li>
            <li>
              For the performance of a contract: for products, items or services
              You have purchased.
            </li>
            <li>
              To contact You: By email, telephone calls, SMS, or other
              equivalent forms of electronic communication.
            </li>
            <li>
              To provide You with news, special offers and general information
              about other goods, services and events.
            </li>
            <li>
              To manage Your requests: To attend and manage Your requests to Us.
            </li>
            <li>
              For business transfers: In connection with any merger, sale of
              Company assets, financing, or acquisition.
            </li>
            <li>
              For other purposes: Such as data analysis, identifying usage
              trends, and improving our Service.
            </li>
          </ul>
        </section>

        {/* Data Sharing */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Sharing of Your Personal Data
          </h2>
          <p className="text-gray-600 mb-4">
            We may share Your personal information in the following situations:
          </p>
          <ul className="list-disc pl-8 space-y-2 text-gray-600">
            <li>
              With Service Providers: To monitor and analyze the use of our
              Service.
            </li>
            <li>
              For business transfers: In connection with any merger, sale of
              Company assets, financing, or acquisition.
            </li>
            <li>
              With Affiliates: With Our affiliates, requiring them to honor this
              Privacy Policy.
            </li>
            <li>
              With business partners: To offer You certain products, services or
              promotions.
            </li>
            <li>
              With other users: When You share information in public areas.
            </li>
            <li>With Your consent: For any other purpose with Your consent.</li>
          </ul>
        </section>

        {/* Data Retention */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Retention of Your Personal Data
          </h2>
          <p className="text-gray-600 mb-2">
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
          <p className="text-gray-600">
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </p>
        </section>

        {/* Data Transfer */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Transfer of Your Personal Data
          </h2>
          <p className="text-gray-600">
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. Your consent to this
            Privacy Policy followed by Your submission of such information
            represents Your agreement to that transfer.
          </p>
          <p className="mt-2 text-gray-600">
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy.
          </p>
        </section>

        {/* Delete Personal Data */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Delete Your Personal Data
          </h2>
          <p className="text-gray-600">
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about You. You may update,
            amend, or delete Your information at any time by signing in to Your
            Account and visiting the account settings section.
          </p>
          <p className="mt-2 text-gray-600">
            Please note, however, that We may need to retain certain information
            when we have a legal obligation or lawful basis to do so.
          </p>
        </section>

        {/* Disclosure of Personal Data */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Disclosure of Your Personal Data
          </h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium mb-2">
                Business Transactions
              </h3>
              <p className="text-gray-600">
                If the Company is involved in a merger, acquisition or asset
                sale, Your Personal Data may be transferred.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium mb-2">Law Enforcement</h3>
              <p className="text-gray-600">
                Under certain circumstances, the Company may be required to
                disclose Your Personal Data if required to do so by law or in
                response to valid requests by public authorities.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium mb-2">
                Other Legal Requirements
              </h3>
              <p className="text-gray-600">
                The Company may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
              </p>
              <ul className="list-disc pl-8 mt-2 space-y-1 text-gray-600">
                <li>Comply with a legal obligation</li>
                <li>
                  Protect and defend the rights or property of the Company
                </li>
                <li>Prevent or investigate possible wrongdoing</li>
                <li>Protect the personal safety of Users or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Security */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Security of Your Personal Data
          </h2>
          <p className="text-gray-600">
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
        </section>

        {/* Children's Privacy */}
        <section>
          <h2 className="text-xl font-semibold mb-4">Children's Privacy</h2>
          <p className="text-gray-600">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us.
          </p>
        </section>

        {/* Links to Other Websites */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Links to Other Websites
          </h2>
          <p className="text-gray-600">
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className="mt-2 text-gray-600">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </section>

        {/* Changes to Privacy Policy */}
        <section>
          <h2 className="text-xl font-semibold mb-4">
            Changes to this Privacy Policy
          </h2>
          <p className="text-gray-600">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page
            and update the "Last updated" date at the top of this Privacy
            Policy.
          </p>
          <p className="mt-2 text-gray-600">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        {/* Contact Information */}
        <section className="border-t pt-6">
          <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
          <p className="text-gray-600">
            If you have any questions about this Privacy Policy, You can contact
            us:
            <br />
            By email:{" "}
            <a
              href="mailto:blj.jambi24@bljambi.com"
              className="text-blue-600 hover:underline"
            >
              blj.jambi24@bljambi.com
            </a>
          </p>
        </section>
      </div>
    </div>
  )
}

export default PrivacyPolicy
